css/style.css
- for colors and fonts the are used more than once
=> variables added

Projects.html, about.html, blog-single.html, blog.html, contact.html, index.html
Changing testimonials to Projects on all headers for pages
=> added testimonials tab

contact.html
Reverts CirroCloudLtd/CirroCloudLtd.github.io#26
=> Revert "location added"

Projects.html, about.html, blog.html, contact.html, css/styles.css, index.html, services.html
Changed the footer and top nav on all pages, edit some sections of the  home page.
Google analytics added
=> Top Nav and Footer Changes

Projects.html, about.html, blog.html, contact.html, index.html, services.html
Created analytics using our google email
=> Adding Google analytics

css/styles.css
Removed the paragraph from the footer and put a slogan
=> Footer changes

css/styles.css, images/gifs/index.html, index.html
=> copyright changes

index.html
Removed code from css folder to the  the home page direclty because it was not reflecting
=> Top nav and footer

about.html, index.html
Adding the footer and top nav code on all pages
=> common footer

index.html
Home page had repeated sections , iam replacing them
=> Hiome page adjustiments

Projects.html, about.html, blog.html, contact.html, services.html
Footer has been made uniform on all pages
=> Uniform Footer

index.html
This reverts commit 4220027196bf18444e6959517975dfc318c7004c, reversing changes made to aa70b0f37c1e27aa8eaeba89c2cd83806afac03c.
=> Revert "Merge pull request #55 from jhermeel/HOME-IMAGE-"

Projects.html, about.html, blog.html, contact.html, index.html, services.html
=> contactus 

about.html, contact.html
=> create contact pages

about.html, adoption.html, blog.html, business.html, contact.html, data.html, digital.html, efris.html, index.html, jamie/jamie.css, modern.html, products.html, services.html, support.html, training.html
Includes changes in index and products page plus all changes in dropdown menu for all pages
=> index and products page

azure.html, efris.html, index.html, nav.html, products.html
Iam removing the repeated sections from the home page and adding the css in the jamie css file to have sections the way they are supposed to be
=> Home page ans products pages

Projects.html, about.html, adoption.html, azure.html, blog-details.html, blog-form.html, blog.html, business.html, contact.html, data.html, digital.html, efris.html, index.html, modern.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
correct title and errors in spelling
=> correct errors

about.html, adoption.html, azure.html, blog.html, business.html, contact.html, data.html, digital.html, efris.html, index.html, modern.html, nav.html, products.html, services.html, support.html, training.html
=> corrections

index.html
image  doesnt display- being fixed
=> image  doesnt display

jamie/jamie.css
drop down disappears-being worked on
=> drop down disappears

index.html, jamie/jamie.css
Adding request for a demo section on the home page
=> Demo section

index.html, modern.html
updated a few keywords and added blogpost schema
=> seo updates

css/styles.css, index.html, jamie/jamie.css
have updated the home page sections for demo and business automation
=> updating homepage

index.html, jamie/jamie.css, jamie/jamieslider.js
new words to describe products on slider
=> new azure image and desc words

jamie/jamie.css
Improving the look of partners section
=> Partners correction

about.html, azure.html, business.html, data.html, digital.html, document.html, index.html, modern.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
added a new service called document management
=> document management service added

index.html
=> partners 3

index.html
=> index restoring old changes

index.html
=> chatboat removal

Projects.html, about.html, adoption.html, azure.html, business.html, contact.html, data.html, digital.html, efris.html, index.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
Placed keywords on all the html pages.
=> added keywords

jamie/jamie.css
Reverts CirroCloudLtd/CirroCloudLtd.github.io#167
=> Revert "Update jamie.css"

index.html
=> adding new partners

index.html
=> Chatboat update

Projects.html, about.html, adoption.html, azure.html, blog-details.html, blog.html, business.html, contact.html, data.html, digital.html, document.html, efris.html, index.html, modern.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
=> change contacts

Projects.html, about.html, adoption.html, azure.html, blog-details.html, blog.html, business.html, contact.html, data.html, digital.html, document.html, efris.html, index.html, modern.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
=> new contact s

Projects.html, adoption.html, azure.html, blog-details.html, blog.html, business.html, contact.html, data.html, digital.html, document.html, efris.html, index.html, modern.html, nav.html, office.html, power.html, products.html, services.html, support.html, training.html
=> Footer contact changes
